#!/usr/bin/env python3
import sys
import example
import Xlsx

first = True
for sheet in example.SHEETS:
    if not first:
        print('\f')
    first = False
    Xlsx.sheet_to_tsv(sheet, sys.stdout)
